name: Build and Trigger Jobs

on:
  schedule:
    - cron: '0 11 * * 1'  # Triggers Job1: Every Monday at 4:30 PM IST (11:00 AM UTC)
    - cron: '45 18 * * 2'  # Triggers Job2: Every Tuesday at 12:15 AM IST (6:45 PM UTC previous day)
    - cron: '50 2 * * 3'  # Triggers Job3: Every Wednesday at 8:20 AM IST (2:50 AM UTC)
    - cron: '0 11 * * 4'  # Triggers Job4: Every Thursday at 4:30 PM IST (11:00 AM UTC)
    - cron: '45 18 * * 5'  # Triggers Job5: Every Friday at 12:15 AM IST (6:45 PM UTC previous day)
    - cron: '50 2 * * 6'  # Triggers Job6: Every Saturday at 8:20 AM IST (2:50 AM UTC)
    - cron: '45 18 * * 0'  # Triggers Job7: Every Sunday at 12:15 AM IST (6:45 PM UTC previous day)
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  trigger_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Debugging Step
        run: |
          echo "Repository Owner: ${{ env.REPO_OWNER }}"
          echo "Repository Name: ${{ env.REPO_NAME }}"

      - name: Trigger Job1 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/job1.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Job2 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/job2.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Job3 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/job3.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Job4 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/job4.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Job5 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/job5.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Job6 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/job6.yml/dispatches \
          -d '{"ref":"main"}'

      - name: Trigger Job7 Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/job7.yml/dispatches \
          -d '{"ref":"main"}'
